# Generated by Django 2.2.5 on 2020-05-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_code', models.CharField(max_length=15)),
                ('Outcome_no', models.IntegerField()),
                ('Outcome_Text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course_units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_code', models.CharField(max_length=15)),
                ('Unit_num', models.CharField(max_length=100)),
                ('Unit_name', models.CharField(max_length=50)),
                ('Unit_Details', models.CharField(max_length=50)),
                ('Unit_marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('Course_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Course_type', models.CharField(max_length=3)),
                ('Course_name', models.CharField(max_length=50)),
                ('Course_exam', models.CharField(max_length=15)),
                ('Dept_id', models.CharField(max_length=10)),
                ('Course_marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Depart_Teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teach_id', models.CharField(max_length=10)),
                ('Dept_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Dept_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Dept_name', models.CharField(max_length=100)),
                ('Dept_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedQpRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_name', models.TextField(blank=True, null=True)),
                ('File_loc', models.TextField(blank=True, null=True)),
                ('File_author', models.CharField(max_length=30)),
                ('Dept_id', models.CharField(max_length=10)),
                ('Creation_Date', models.CharField(blank=True, max_length=30, null=True)),
                ('Course_code', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mcq_instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_id', models.IntegerField()),
                ('Text', models.TextField(null=True)),
                ('Exam_record', models.TextField(null=True)),
                ('Exam_date', models.CharField(max_length=50, null=True)),
                ('Course_code', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quest_BankMCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_code', models.CharField(max_length=15)),
                ('Qtext', models.TextField(null=True)),
                ('choice_1', models.CharField(max_length=50, null=True)),
                ('choice_2', models.CharField(max_length=50, null=True)),
                ('choice_3', models.CharField(max_length=50, null=True)),
                ('choice_4', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='diagrams/%Y/%m/%d')),
                ('BloomL', models.IntegerField(blank=True, null=True)),
                ('Co', models.IntegerField(blank=True, null=True)),
                ('unit_num', models.IntegerField(blank=True, null=True)),
                ('max_marks', models.IntegerField(blank=True, null=True)),
                ('min_marks', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(max_length=40, null=True)),
                ('State', models.CharField(max_length=5)),
                ('RefCount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quest_BankTHR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_code', models.CharField(max_length=15)),
                ('Qtext', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='diagrams/%Y/%m/%d')),
                ('BloomL', models.IntegerField(blank=True, null=True)),
                ('Co', models.IntegerField(blank=True, null=True)),
                ('unit_num', models.IntegerField(blank=True, null=True)),
                ('max_marks', models.IntegerField(blank=True, null=True)),
                ('min_marks', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(max_length=40, null=True)),
                ('State', models.CharField(max_length=5)),
                ('RefCount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teach_Course_MR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teach_id', models.CharField(max_length=10)),
                ('Course_code', models.CharField(max_length=15)),
                ('Rights', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('Teach_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Teach_name', models.CharField(max_length=50)),
                ('Teach_uname', models.CharField(max_length=50)),
                ('Teach_pass', models.CharField(max_length=50)),
                ('Rights', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theory_instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_id', models.IntegerField()),
                ('Text', models.TextField(null=True)),
                ('Exam_record', models.TextField(null=True)),
                ('Exam_date', models.CharField(max_length=50, null=True)),
                ('Course_code', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
