# Generated by Django 2.2.5 on 2020-05-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teach_course_mr',
            name='Dept_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
