# Generated by Django 2.2.5 on 2020-05-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_teach_course_mr_dept_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='Dept_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
