# Generated by Django 2.2.5 on 2020-05-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_teachers_dept_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teach_course_mr',
            name='Teach_uname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
