# Generated by Django 2.2.5 on 2020-05-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_remove_teach_course_mr_teach_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teach_course_mr',
            name='Course_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
