# Generated by Django 2.2.5 on 2020-05-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_teach_course_mr_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedqprec',
            name='mcqArray',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generatedqprec',
            name='thrArray',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
