# Generated by Django 2.2.5 on 2020-05-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_generatedqprec_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedqprec',
            name='sample',
        ),
        migrations.AlterField(
            model_name='generatedqprec',
            name='mcqArray',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='generatedqprec',
            name='thrArray',
            field=models.BinaryField(null=True),
        ),
    ]
