# Generated by Django 2.2.5 on 2020-05-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_auto_20200515_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedqprec',
            name='verify',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='generatedqprec',
            name='mcqArray',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generatedqprec',
            name='thrArray',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
