# Generated by Django 2.2.5 on 2020-05-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_auto_20200515_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq_instance',
            name='Text',
        ),
        migrations.RemoveField(
            model_name='theory_instance',
            name='Text',
        ),
    ]
