# Generated by Django 2.2.5 on 2020-05-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_auto_20200515_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedqprec',
            name='Exam_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
