# Generated by Django 2.2.5 on 2020-05-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_generatedqprec_exam_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='Course_exam',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='Course_marks',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='Course_type',
        ),
        migrations.AddField(
            model_name='teach_course_mr',
            name='Teach_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
